/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mars_sol-116_terrain_area_with_ingenuity.glb 
Author: Owl Creek Technologies (https://sketchfab.com/mebalzer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mars-sol-116-terrain-area-with-ingenuity-fb04d8529c7846119ebf322bfc6c5ed9
Title: Mars SOL-116 Terrain Area with Ingenuity
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Mars(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('models/mars_sol-116_terrain_area_with_ingenuity.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => void actions['Animation'].play(), [actions])  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 1.65, 0, 0]} position={[0, -0.5, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="baked_mesh_4" rotation={[Math.PI / 2, 0, 0]}>
                <group name="Geom_3">
                  <group name="g0_2" scale={[10, 10, 10.01]}>
                    <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.material} />
                  </group>
                </group>
              </group>
              <group name="Armature_10" position={[0, 0.2, 0]} scale={0.01}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Ingenuity_9" />
                  {/*disabled <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Ingenuity_Material} skeleton={nodes.Object_11.skeleton} />*/}
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/mars_sol-116_terrain_area_with_ingenuity.glb')
