/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/wall-eanimated.glb 
Author: Janis Zeps (https://sketchfab.com/Zeps3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wall-eanimated-a6758de2e5a04f9e821596592ef4279c
Title: Wall-E(Animated)
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function WallE(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('models/wall-eanimated.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => void actions['Scene'].play(), [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 1.65, 0, 0]}>
          <group name="0d517e7ed53f4f858caad58d3bacd985fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.0028} position={[0,1.5,-0.50]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="trackGears1_low" position={[0, 49.736, -85.991]} rotation={[2.199, 0, 0]} scale={100}>
                  <mesh name="trackGears1_low_wall_e_0" geometry={nodes.trackGears1_low_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="eyes_low" position={[0, 390.621, -34.013]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="eyes_low_wall_e_0" geometry={nodes.eyes_low_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="neck_low" position={[0, 298.642, -50.859]} rotation={[-1.726, 0, 0]} scale={100}>
                  <mesh name="neck_low_wall_e_0" geometry={nodes.neck_low_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="hand_low" position={[-150.622, 272.83, -20.012]} rotation={[-2.184, 0, 0]} scale={100}>
                  <mesh name="hand_low_wall_e_0" geometry={nodes.hand_low_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="trackGears2_low" position={[0, 46.014, 69.712]} rotation={[2.199, 0, 0]} scale={[100, 89.327, 89.327]}>
                  <mesh name="trackGears2_low_wall_e_0" geometry={nodes.trackGears2_low_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="trackGears4_low" position={[0, 160.093, -59.865]} rotation={[2.199, 0, 0]} scale={[100, 69.853, 69.853]}>
                  <mesh name="trackGears4_low_wall_e_0" geometry={nodes.trackGears4_low_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="trackGears3_low" position={[0, 111.774, 33.006]} rotation={[2.199, 0, 0]} scale={[100, 54.081, 54.081]}>
                  <mesh name="trackGears3_low_wall_e_0" geometry={nodes.trackGears3_low_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="eyes_low001" position={[0, 390.621, -0.964]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="eyes_low001_eyes_0" geometry={nodes.eyes_low001_eyes_0.geometry} material={materials.eyes} />
                </group>
                <group name="hand_low001" position={[149.804, 248.002, -56.568]} rotation={[-1.454, 0, 0]} scale={100}>
                  <mesh name="hand_low001_wall_e_0" geometry={nodes.hand_low001_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="hand_low002" position={[-93.375, 396.861, 157.785]} rotation={[-1.625, 0, 0]} scale={100}>
                  <mesh name="hand_low002_wall_e_0" geometry={nodes.hand_low002_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low" position={[0.236, 85.077, 92.35]} rotation={[2.512, -0.009, 0]} scale={100}>
                  <mesh name="track_low_wall_e_0" geometry={nodes.track_low_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low001" position={[0.244, 103.849, 76.206]} rotation={[2.378, -0.009, 0]} scale={100}>
                  <mesh name="track_low001_wall_e_0" geometry={nodes.track_low001_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low002" position={[0.255, 120.858, 58.148]} rotation={[2.289, -0.009, 0.001]} scale={100}>
                  <mesh name="track_low002_wall_e_0" geometry={nodes.track_low002_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low003" position={[0.27, 136.581, 38.793]} rotation={[2.238, -0.009, 0.002]} scale={100}>
                  <mesh name="track_low003_wall_e_0" geometry={nodes.track_low003_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low004" position={[0.383, 152.096, 18.393]} rotation={[2.211, -0.01, 0.007]} scale={100}>
                  <mesh name="track_low004_wall_e_0" geometry={nodes.track_low004_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low005" position={[0.054, 58.341, -129.458]} rotation={[0.008, 0, 0.003]} scale={100}>
                  <mesh name="track_low005_wall_e_0" geometry={nodes.track_low005_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low006" position={[0.786, 179.067, -22.681]} rotation={[2.04, -0.012, 0.007]} scale={100}>
                  <mesh name="track_low006_wall_e_0" geometry={nodes.track_low006_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low007" position={[0.885, 187.6, -44.067]} rotation={[1.801, -0.013, -0.001]} scale={100}>
                  <mesh name="track_low007_wall_e_0" geometry={nodes.track_low007_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low008" position={[0.722, 188.394, -65.821]} rotation={[1.309, -0.009, -0.018]} scale={100}>
                  <mesh name="track_low008_wall_e_0" geometry={nodes.track_low008_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low009" position={[0.162, 175.672, -86.663]} rotation={[0.679, 0, -0.015]} scale={100}>
                  <mesh name="track_low009_wall_e_0" geometry={nodes.track_low009_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low010" position={[-0.038, 152.5, -100.915]} rotation={[0.486, 0.001, -0.004]} scale={100}>
                  <mesh name="track_low010_wall_e_0" geometry={nodes.track_low010_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low011" position={[-0.067, 127.615, -113.09]} rotation={[0.39, 0.001, 0]} scale={100}>
                  <mesh name="track_low011_wall_e_0" geometry={nodes.track_low011_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low012" position={[-0.054, 104.51, -122.937]} rotation={[0.3, 0.001, 0.001]} scale={100}>
                  <mesh name="track_low012_wall_e_0" geometry={nodes.track_low012_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low013" position={[0.589, 167.261, 0.044]} rotation={[2.163, -0.011, 0.009]} scale={100}>
                  <mesh name="track_low013_wall_e_0" geometry={nodes.track_low013_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low014" position={[-0.028, 82.795, -128.361]} rotation={[0.185, 0, 0.003]} scale={100}>
                  <mesh name="track_low014_wall_e_0" geometry={nodes.track_low014_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low015" position={[0.142, 33.615, -128.53]} rotation={[-0.306, -0.002, 0.004]} scale={100}>
                  <mesh name="track_low015_wall_e_0" geometry={nodes.track_low015_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low016" position={[0.229, 13.143, -115.667]} rotation={[-0.862, -0.004, 0.003]} scale={100}>
                  <mesh name="track_low016_wall_e_0" geometry={nodes.track_low016_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low017" position={[0.269, 3.261, -93.534]} rotation={[-1.345, -0.005, 0.001]} scale={100}>
                  <mesh name="track_low017_wall_e_0" geometry={nodes.track_low017_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low018" position={[0.28, 1.513, -68.914]} rotation={[-1.585, -0.006, 0]} scale={100}>
                  <mesh name="track_low018_wall_e_0" geometry={nodes.track_low018_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low019" position={[0.273, 2.748, -44.091]} rotation={[-1.624, -0.006, 0]} scale={100}>
                  <mesh name="track_low019_wall_e_0" geometry={nodes.track_low019_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low020" position={[0.272, 4.185, -19.052]} rotation={[-1.606, -0.007, 0]} scale={100}>
                  <mesh name="track_low020_wall_e_0" geometry={nodes.track_low020_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low021" position={[0.721, 189.298, -65.894]} rotation={[1.351, -0.01, -0.017]} scale={100}>
                  <mesh name="track_low021_wall_e_0" geometry={nodes.track_low021_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low022" position={[0.271, 4.795, 6.045]} rotation={[-1.57, -0.007, 0]} scale={100}>
                  <mesh name="track_low022_wall_e_0" geometry={nodes.track_low022_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low023" position={[0.276, 4.293, 30.851]} rotation={[-1.532, -0.007, 0]} scale={100}>
                  <mesh name="track_low023_wall_e_0" geometry={nodes.track_low023_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low024" position={[0.27, 3.061, 55.616]} rotation={[-1.555, -0.008, 0]} scale={100}>
                  <mesh name="track_low024_wall_e_0" geometry={nodes.track_low024_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low025" position={[0.265, 5.258, 80.222]} rotation={[-1.835, -0.008, 0]} scale={100}>
                  <mesh name="track_low025_wall_e_0" geometry={nodes.track_low025_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low026" position={[0.252, 17.054, 101.679]} rotation={[-2.394, -0.008, -0.001]} scale={100}>
                  <mesh name="track_low026_wall_e_0" geometry={nodes.track_low026_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low027" position={[0.238, 39.655, 110.598]} rotation={[-3.111, -0.008, 0]} scale={100}>
                  <mesh name="track_low027_wall_e_0" geometry={nodes.track_low027_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="track_low028" position={[0.232, 63.8, 105.138]} rotation={[2.736, -0.008, 0]} scale={100}>
                  <mesh name="track_low028_wall_e_0" geometry={nodes.track_low028_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="body_low" position={[0, 182.179, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="body_low_wall_e_0" geometry={nodes.body_low_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="back_low" position={[0, 180.11, -92.204]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="back_low_wall_e_0" geometry={nodes.back_low_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="base_low" position={[0, 80.624, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={205.08}>
                  <mesh name="base_low_wall_e_0" geometry={nodes.base_low_wall_e_0.geometry} material={materials.wall_e} />
                </group>
                <group name="trackDetails001_low" position={[-0.788, -11.52, -10.637]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="trackDetails001_low_wall_e_0" geometry={nodes.trackDetails001_low_wall_e_0.geometry} material={materials.wall_e} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/wall-eanimated.glb')
